-- MySQL Script generated by MySQL Workbench
-- Mon Dec 28 22:07:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecopick
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecopick
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecopick` DEFAULT CHARACTER SET utf8 ;
USE `ecopick` ;

-- -----------------------------------------------------
-- Table `ecopick`.`lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecopick`.`lugar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `tipo` INT NOT NULL,
  `fk_lugar` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lugar_lugar_idx` (`fk_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_lugar_lugar`
    FOREIGN KEY (`fk_lugar`)
    REFERENCES `ecopick`.`lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecopick`.`preguntaseguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecopick`.`preguntaseguridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecopick`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecopick`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NULL,
  `email` VARCHAR(90) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL,
  `FechaNacimiento` DATE NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL,
  `NumeroIdentificacion` VARCHAR(45) NOT NULL,
  `RespuestaSeguridad` VARCHAR(90) NOT NULL,
  `fk_lugar` INT NOT NULL,
  `fk_pregunta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_lugar_idx` (`fk_lugar` ASC) VISIBLE,
  INDEX `fk_usuario_pregunta_idx` (`fk_pregunta` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_lugar`
    FOREIGN KEY (`fk_lugar`)
    REFERENCES `ecopick`.`lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pregunta`
    FOREIGN KEY (`fk_pregunta`)
    REFERENCES `ecopick`.`preguntaseguridad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
